export const config = {
	ERROR: {
		AUTH: {
			UNAUTHORIZED: "Unauthorized",
			INVALID_TOKEN: "Invalid token",
			REGISTRATION_VALIDATION_FAILED: "Registration validation failed",
			LOGIN_VALIDATION_FAILED: "Login validation failed",
			PASSWORD_UPDATE_VALIDATION_FAILED: "Password update validation failed",
			FIRST_NAME_LAST_NAME_REQUIRED: "First name and last name are required",
			INVALID_ORGANIZATION_ID_FORMAT: "Invalid organization ID format",
			ORGANIZATION_NOT_FOUND: "Organization not found",
			USER_ALREADY_EXISTS: "User already exists",
			ERROR_DURING_REGISTRATION: "Error during registration",
			INVALID_CREDENTIALS: "Invalid credentials",
			ERROR_DURING_LOGIN: "Error during login",
			USER_ID_PASSWORD_REQUIRED: "User ID and new password are required",
			PASSWORD_MIN_LENGTH: "Password must be at least 6 characters long",
			ERROR_UPDATING_PASSWORD: "Error updating password",
			USER_NOT_FOUND: "User not found",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
		},
		TEMPLATE: {
			VALIDATION_FAILED: "Template validation failed",
			INVALID_ID_FORMAT: "Invalid template ID format",
			NOT_FOUND: "Template not found",
			CREATE_FAILED: "Error creating template",
			UPDATE_FAILED: "Error updating template",
			DELETE_FAILED: "Error deleting template",
			GET_FAILED: "Error getting template",
			GET_ALL_FAILED: "Error getting templates",
			ERROR_GETTING: "Error getting template",
			ERROR_UPDATING: "Error updating template",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		QUERY_PARAMS: {
			MISSING_ID: "ID parameter is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate must be a string",
			INVALID_PAGE: "Invalid page",
			INVALID_LIMIT: "Invalid limit",
			INVALID_ORDER: "Invalid order",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
			INVALID_SORT: "Invalid sort",
			SORT_MUST_BE_STRING: "Sort must be a string",
			INVALID_FILTER: "Invalid filter",
			FILTER_MUST_BE_STRING: "Filter must be a string",
			INVALID_QUERY: "Invalid query",
			QUERY_MUST_BE_STRING: "Query must be a string",
			INVALID_DOCUMENT: "Invalid document",
			DOCUMENT_MUST_BE_STRING: "Document must be a string",
			INVALID_PAGINATION: "Invalid pagination",
			PAGINATION_MUST_BE_STRING: "Pagination must be a string",
			INVALID_COUNT: "Invalid count",
			COUNT_MUST_BE_STRING: "Count must be a string",
			INVALID_GROUPBY: "Invalid groupBy",
			INVALID_COMBINATION: "Invalid combination",
		},
		COMMON: {
			INTERNAL_SERVER_ERROR: "Internal server error",
			VALIDATION_ERROR: "Validation error",
			NOT_FOUND: "Resource not found",
			UNAUTHORIZED: "Unauthorized access",
			NO_UPDATE_FIELDS: "No fields provided for update",
		},
		WALLET: {
			VALIDATION_FAILED: "Wallet validation failed",
			INVALID_ID_FORMAT: "Invalid wallet ID format",
			NOT_FOUND: "Wallet not found",
			CREATE_FAILED: "Error creating wallet",
			UPDATE_FAILED: "Error updating wallet",
			DELETE_FAILED: "Error deleting wallet",
			GET_FAILED: "Error getting wallet",
			GET_ALL_FAILED: "Error getting wallets",
			ERROR_GETTING: "Error getting wallet",
			ERROR_UPDATING: "Error updating wallet",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		KYC: {
			VALIDATION_FAILED: "Kyc validation failed",
			INVALID_ID_FORMAT: "Invalid kyc ID format",
			NOT_FOUND: "Kyc not found",
			CREATE_FAILED: "Error creating kyc",
			UPDATE_FAILED: "Error updating kyc",
			DELETE_FAILED: "Error deleting kyc",
			GET_FAILED: "Error getting kyc",
			GET_ALL_FAILED: "Error getting kycs",
			ERROR_GETTING: "Error getting kyc",
			ERROR_UPDATING: "Error updating kyc",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		SESSION: {
			VALIDATION_FAILED: "Session validation failed",
			INVALID_ID_FORMAT: "Invalid session ID format",
			NOT_FOUND: "Session not found",
			CREATE_FAILED: "Error creating session",
			UPDATE_FAILED: "Error updating session",
			DELETE_FAILED: "Error deleting session",
			GET_FAILED: "Error getting session",
			GET_ALL_FAILED: "Error getting sessions",
			ERROR_GETTING: "Error getting session",
			ERROR_UPDATING: "Error updating session",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		AGENT: {
			VALIDATION_FAILED: "Agent validation failed",
			INVALID_ID_FORMAT: "Invalid agent ID format",
			NOT_FOUND: "Agent not found",
			CREATE_FAILED: "Error creating agent",
			UPDATE_FAILED: "Error updating agent",
			DELETE_FAILED: "Error deleting agent",
			GET_FAILED: "Error getting agent",
			GET_ALL_FAILED: "Error getting agents",
			ERROR_GETTING: "Error getting agent",
			ERROR_UPDATING: "Error updating agent",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		TERRITORY: {
			VALIDATION_FAILED: "Territory validation failed",
			INVALID_ID_FORMAT: "Invalid territory ID format",
			NOT_FOUND: "Territory not found",
			CREATE_FAILED: "Error creating territory",
			UPDATE_FAILED: "Error updating territory",
			DELETE_FAILED: "Error deleting territory",
			GET_FAILED: "Error getting territory",
			GET_ALL_FAILED: "Error getting territorys",
			ERROR_GETTING: "Error getting territory",
			ERROR_UPDATING: "Error updating territory",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		DRAWSCHEDULE: {
			VALIDATION_FAILED: "DrawSchedule validation failed",
			INVALID_ID_FORMAT: "Invalid drawschedule ID format",
			NOT_FOUND: "DrawSchedule not found",
			CREATE_FAILED: "Error creating drawschedule",
			UPDATE_FAILED: "Error updating drawschedule",
			DELETE_FAILED: "Error deleting drawschedule",
			GET_FAILED: "Error getting drawschedule",
			GET_ALL_FAILED: "Error getting drawschedules",
			ERROR_GETTING: "Error getting drawschedule",
			ERROR_UPDATING: "Error updating drawschedule",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		JUETENGDRAW: {
			VALIDATION_FAILED: "JuetengDraw validation failed",
			INVALID_ID_FORMAT: "Invalid juetengdraw ID format",
			NOT_FOUND: "JuetengDraw not found",
			CREATE_FAILED: "Error creating juetengdraw",
			UPDATE_FAILED: "Error updating juetengdraw",
			DELETE_FAILED: "Error deleting juetengdraw",
			GET_FAILED: "Error getting juetengdraw",
			GET_ALL_FAILED: "Error getting juetengdraws",
			ERROR_GETTING: "Error getting juetengdraw",
			ERROR_UPDATING: "Error updating juetengdraw",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		JUETENGBET: {
			VALIDATION_FAILED: "JuetengBet validation failed",
			INVALID_ID_FORMAT: "Invalid juetengbet ID format",
			NOT_FOUND: "JuetengBet not found",
			CREATE_FAILED: "Error creating juetengbet",
			UPDATE_FAILED: "Error updating juetengbet",
			DELETE_FAILED: "Error deleting juetengbet",
			GET_FAILED: "Error getting juetengbet",
			GET_ALL_FAILED: "Error getting juetengbets",
			ERROR_GETTING: "Error getting juetengbet",
			ERROR_UPDATING: "Error updating juetengbet",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		JUETENGCONFIG: {
			VALIDATION_FAILED: "JuetengConfig validation failed",
			INVALID_ID_FORMAT: "Invalid juetengconfig ID format",
			NOT_FOUND: "JuetengConfig not found",
			CREATE_FAILED: "Error creating juetengconfig",
			UPDATE_FAILED: "Error updating juetengconfig",
			DELETE_FAILED: "Error deleting juetengconfig",
			GET_FAILED: "Error getting juetengconfig",
			GET_ALL_FAILED: "Error getting juetengconfigs",
			ERROR_GETTING: "Error getting juetengconfig",
			ERROR_UPDATING: "Error updating juetengconfig",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		JUETENGPAYOUT: {
			VALIDATION_FAILED: "JuetengPayout validation failed",
			INVALID_ID_FORMAT: "Invalid juetengpayout ID format",
			NOT_FOUND: "JuetengPayout not found",
			CREATE_FAILED: "Error creating juetengpayout",
			UPDATE_FAILED: "Error updating juetengpayout",
			DELETE_FAILED: "Error deleting juetengpayout",
			GET_FAILED: "Error getting juetengpayout",
			GET_ALL_FAILED: "Error getting juetengpayouts",
			ERROR_GETTING: "Error getting juetengpayout",
			ERROR_UPDATING: "Error updating juetengpayout",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		COMMISSION: {
			VALIDATION_FAILED: "Commission validation failed",
			INVALID_ID_FORMAT: "Invalid commission ID format",
			NOT_FOUND: "Commission not found",
			CREATE_FAILED: "Error creating commission",
			UPDATE_FAILED: "Error updating commission",
			DELETE_FAILED: "Error deleting commission",
			GET_FAILED: "Error getting commission",
			GET_ALL_FAILED: "Error getting commissions",
			ERROR_GETTING: "Error getting commission",
			ERROR_UPDATING: "Error updating commission",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		NOTIFICATION: {
			VALIDATION_FAILED: "Notification validation failed",
			INVALID_ID_FORMAT: "Invalid notification ID format",
			NOT_FOUND: "Notification not found",
			CREATE_FAILED: "Error creating notification",
			UPDATE_FAILED: "Error updating notification",
			DELETE_FAILED: "Error deleting notification",
			GET_FAILED: "Error getting notification",
			GET_ALL_FAILED: "Error getting notifications",
			ERROR_GETTING: "Error getting notification",
			ERROR_UPDATING: "Error updating notification",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
	},

	SUCCESS: {
		AUTH: {
			REGISTRATION_SUCCESSFUL: "Registration successful",
			LOGGED_IN_SUCCESSFULLY: "Logged in successfully",
			PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
			USER_CREATED: "User created successfully",
			TOKEN_GENERATED: "Token generated successfully",
			ORGANIZATION_VERIFIED: "Organization verified successfully",
			USER_LOGGED_IN: "User logged in successfully",
		},
		TEMPLATE: {
			CREATED: "Template created successfully",
			UPDATED: "Template updated successfully",
			DELETED: "Template deleted successfully",
			RETRIEVED: "Template retrieved successfully",
			RETRIEVED_ALL: "Templates retrieved successfully",
			GETTING_BY_ID: "Getting template by ID",
		},
		COMMON: {
			OPERATION_SUCCESSFUL: "Operation completed successfully",
		},
		WALLET: {
			CREATED: "Wallet created successfully",
			UPDATED: "Wallet updated successfully",
			DELETED: "Wallet deleted successfully",
			RETRIEVED: "Wallet retrieved successfully",
			RETRIEVED_ALL: "Wallets retrieved successfully",
			GETTING_BY_ID: "Getting wallet by ID",
		},
		KYC: {
			CREATED: "Kyc created successfully",
			UPDATED: "Kyc updated successfully",
			DELETED: "Kyc deleted successfully",
			RETRIEVED: "Kyc retrieved successfully",
			RETRIEVED_ALL: "Kycs retrieved successfully",
			GETTING_BY_ID: "Getting kyc by ID",
		},
		SESSION: {
			CREATED: "Session created successfully",
			UPDATED: "Session updated successfully",
			DELETED: "Session deleted successfully",
			RETRIEVED: "Session retrieved successfully",
			RETRIEVED_ALL: "Sessions retrieved successfully",
			GETTING_BY_ID: "Getting session by ID",
		},
		AGENT: {
			CREATED: "Agent created successfully",
			UPDATED: "Agent updated successfully",
			DELETED: "Agent deleted successfully",
			RETRIEVED: "Agent retrieved successfully",
			RETRIEVED_ALL: "Agents retrieved successfully",
			GETTING_BY_ID: "Getting agent by ID",
		},
		TERRITORY: {
			CREATED: "Territory created successfully",
			UPDATED: "Territory updated successfully",
			DELETED: "Territory deleted successfully",
			RETRIEVED: "Territory retrieved successfully",
			RETRIEVED_ALL: "Territorys retrieved successfully",
			GETTING_BY_ID: "Getting territory by ID",
		},
		DRAWSCHEDULE: {
			CREATED: "DrawSchedule created successfully",
			UPDATED: "DrawSchedule updated successfully",
			DELETED: "DrawSchedule deleted successfully",
			RETRIEVED: "DrawSchedule retrieved successfully",
			RETRIEVED_ALL: "DrawSchedules retrieved successfully",
			GETTING_BY_ID: "Getting drawschedule by ID",
		},
		JUETENGDRAW: {
			CREATED: "JuetengDraw created successfully",
			UPDATED: "JuetengDraw updated successfully",
			DELETED: "JuetengDraw deleted successfully",
			RETRIEVED: "JuetengDraw retrieved successfully",
			RETRIEVED_ALL: "JuetengDraws retrieved successfully",
			GETTING_BY_ID: "Getting juetengdraw by ID",
		},
		JUETENGBET: {
			CREATED: "JuetengBet created successfully",
			UPDATED: "JuetengBet updated successfully",
			DELETED: "JuetengBet deleted successfully",
			RETRIEVED: "JuetengBet retrieved successfully",
			RETRIEVED_ALL: "JuetengBets retrieved successfully",
			GETTING_BY_ID: "Getting juetengbet by ID",
		},
		JUETENGCONFIG: {
			CREATED: "JuetengConfig created successfully",
			UPDATED: "JuetengConfig updated successfully",
			DELETED: "JuetengConfig deleted successfully",
			RETRIEVED: "JuetengConfig retrieved successfully",
			RETRIEVED_ALL: "JuetengConfigs retrieved successfully",
			GETTING_BY_ID: "Getting juetengconfig by ID",
		},
		JUETENGPAYOUT: {
			CREATED: "JuetengPayout created successfully",
			UPDATED: "JuetengPayout updated successfully",
			DELETED: "JuetengPayout deleted successfully",
			RETRIEVED: "JuetengPayout retrieved successfully",
			RETRIEVED_ALL: "JuetengPayouts retrieved successfully",
			GETTING_BY_ID: "Getting juetengpayout by ID",
		},
		COMMISSION: {
			CREATED: "Commission created successfully",
			UPDATED: "Commission updated successfully",
			DELETED: "Commission deleted successfully",
			RETRIEVED: "Commission retrieved successfully",
			RETRIEVED_ALL: "Commissions retrieved successfully",
			GETTING_BY_ID: "Getting commission by ID",
		},
		NOTIFICATION: {
			CREATED: "Notification created successfully",
			UPDATED: "Notification updated successfully",
			DELETED: "Notification deleted successfully",
			RETRIEVED: "Notification retrieved successfully",
			RETRIEVED_ALL: "Notifications retrieved successfully",
			GETTING_BY_ID: "Getting notification by ID",
		},
	},

	ACTIVITY_LOG: {
		COMMISSION: {
			ACTIONS: {
				CREATE_COMMISSION: "CREATE_COMMISSION",
				GET_ALL_COMMISSION: "GET_ALL_COMMISSION",
				GET_COMMISSION: "GET_COMMISSION",
				UPDATE_COMMISSION: "UPDATE_COMMISSION",
				DELETE_COMMISSION: "DELETE_COMMISSION",
			},
			DESCRIPTIONS: {
				COMMISSION_CREATED: "Created new commission",
				COMMISSION_UPDATED: "Updated commission",
				COMMISSION_DELETED: "Deleted commission",
				COMMISSION_RETRIEVED: "Retrieved commission details",
				COMMISSIONS_RETRIEVED: "Retrieved commission list",
			},
			PAGES: {
				COMMISSION_CREATION: "Commission Creation",
				COMMISSION_UPDATE: "Commission Update",
				COMMISSION_DELETION: "Commission Deletion",
				COMMISSION_DETAILS: "Commission Details",
				COMMISSION_LIST: "Commission List",
			},
		},
		NOTIFICATION: {
			ACTIONS: {
				CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
				GET_ALL_NOTIFICATION: "GET_ALL_NOTIFICATION",
				GET_NOTIFICATION: "GET_NOTIFICATION",
				UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
				DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
			},
			DESCRIPTIONS: {
				NOTIFICATION_CREATED: "Created new notification",
				NOTIFICATION_UPDATED: "Updated notification",
				NOTIFICATION_DELETED: "Deleted notification",
				NOTIFICATION_RETRIEVED: "Retrieved notification details",
				NOTIFICATIONS_RETRIEVED: "Retrieved notification list",
			},
			PAGES: {
				NOTIFICATION_CREATION: "Notification Creation",
				NOTIFICATION_UPDATE: "Notification Update",
				NOTIFICATION_DELETION: "Notification Deletion",
				NOTIFICATION_DETAILS: "Notification Details",
				NOTIFICATION_LIST: "Notification List",
			},
		},
		JUETENGPAYOUT: {
			ACTIONS: {
				CREATE_JUETENGPAYOUT: "CREATE_JUETENGPAYOUT",
				GET_ALL_JUETENGPAYOUT: "GET_ALL_JUETENGPAYOUT",
				GET_JUETENGPAYOUT: "GET_JUETENGPAYOUT",
				UPDATE_JUETENGPAYOUT: "UPDATE_JUETENGPAYOUT",
				DELETE_JUETENGPAYOUT: "DELETE_JUETENGPAYOUT",
			},
			DESCRIPTIONS: {
				JUETENGPAYOUT_CREATED: "Created new juetengpayout",
				JUETENGPAYOUT_UPDATED: "Updated juetengpayout",
				JUETENGPAYOUT_DELETED: "Deleted juetengpayout",
				JUETENGPAYOUT_RETRIEVED: "Retrieved juetengpayout details",
				JUETENGPAYOUTS_RETRIEVED: "Retrieved juetengpayout list",
			},
			PAGES: {
				JUETENGPAYOUT_CREATION: "JuetengPayout Creation",
				JUETENGPAYOUT_UPDATE: "JuetengPayout Update",
				JUETENGPAYOUT_DELETION: "JuetengPayout Deletion",
				JUETENGPAYOUT_DETAILS: "JuetengPayout Details",
				JUETENGPAYOUT_LIST: "JuetengPayout List",
			},
		},
		JUETENGCONFIG: {
			ACTIONS: {
				CREATE_JUETENGCONFIG: "CREATE_JUETENGCONFIG",
				GET_ALL_JUETENGCONFIG: "GET_ALL_JUETENGCONFIG",
				GET_JUETENGCONFIG: "GET_JUETENGCONFIG",
				UPDATE_JUETENGCONFIG: "UPDATE_JUETENGCONFIG",
				DELETE_JUETENGCONFIG: "DELETE_JUETENGCONFIG",
			},
			DESCRIPTIONS: {
				JUETENGCONFIG_CREATED: "Created new juetengconfig",
				JUETENGCONFIG_UPDATED: "Updated juetengconfig",
				JUETENGCONFIG_DELETED: "Deleted juetengconfig",
				JUETENGCONFIG_RETRIEVED: "Retrieved juetengconfig details",
				JUETENGCONFIGS_RETRIEVED: "Retrieved juetengconfig list",
			},
			PAGES: {
				JUETENGCONFIG_CREATION: "JuetengConfig Creation",
				JUETENGCONFIG_UPDATE: "JuetengConfig Update",
				JUETENGCONFIG_DELETION: "JuetengConfig Deletion",
				JUETENGCONFIG_DETAILS: "JuetengConfig Details",
				JUETENGCONFIG_LIST: "JuetengConfig List",
			},
		},
		JUETENGBET: {
			ACTIONS: {
				CREATE_JUETENGBET: "CREATE_JUETENGBET",
				GET_ALL_JUETENGBET: "GET_ALL_JUETENGBET",
				GET_JUETENGBET: "GET_JUETENGBET",
				UPDATE_JUETENGBET: "UPDATE_JUETENGBET",
				DELETE_JUETENGBET: "DELETE_JUETENGBET",
			},
			DESCRIPTIONS: {
				JUETENGBET_CREATED: "Created new juetengbet",
				JUETENGBET_UPDATED: "Updated juetengbet",
				JUETENGBET_DELETED: "Deleted juetengbet",
				JUETENGBET_RETRIEVED: "Retrieved juetengbet details",
				JUETENGBETS_RETRIEVED: "Retrieved juetengbet list",
			},
			PAGES: {
				JUETENGBET_CREATION: "JuetengBet Creation",
				JUETENGBET_UPDATE: "JuetengBet Update",
				JUETENGBET_DELETION: "JuetengBet Deletion",
				JUETENGBET_DETAILS: "JuetengBet Details",
				JUETENGBET_LIST: "JuetengBet List",
			},
		},
		JUETENGDRAW: {
			ACTIONS: {
				CREATE_JUETENGDRAW: "CREATE_JUETENGDRAW",
				GET_ALL_JUETENGDRAW: "GET_ALL_JUETENGDRAW",
				GET_JUETENGDRAW: "GET_JUETENGDRAW",
				UPDATE_JUETENGDRAW: "UPDATE_JUETENGDRAW",
				DELETE_JUETENGDRAW: "DELETE_JUETENGDRAW",
			},
			DESCRIPTIONS: {
				JUETENGDRAW_CREATED: "Created new juetengdraw",
				JUETENGDRAW_UPDATED: "Updated juetengdraw",
				JUETENGDRAW_DELETED: "Deleted juetengdraw",
				JUETENGDRAW_RETRIEVED: "Retrieved juetengdraw details",
				JUETENGDRAWS_RETRIEVED: "Retrieved juetengdraw list",
			},
			PAGES: {
				JUETENGDRAW_CREATION: "JuetengDraw Creation",
				JUETENGDRAW_UPDATE: "JuetengDraw Update",
				JUETENGDRAW_DELETION: "JuetengDraw Deletion",
				JUETENGDRAW_DETAILS: "JuetengDraw Details",
				JUETENGDRAW_LIST: "JuetengDraw List",
			},
		},
		DRAWSCHEDULE: {
			ACTIONS: {
				CREATE_DRAWSCHEDULE: "CREATE_DRAWSCHEDULE",
				GET_ALL_DRAWSCHEDULE: "GET_ALL_DRAWSCHEDULE",
				GET_DRAWSCHEDULE: "GET_DRAWSCHEDULE",
				UPDATE_DRAWSCHEDULE: "UPDATE_DRAWSCHEDULE",
				DELETE_DRAWSCHEDULE: "DELETE_DRAWSCHEDULE",
			},
			DESCRIPTIONS: {
				DRAWSCHEDULE_CREATED: "Created new drawschedule",
				DRAWSCHEDULE_UPDATED: "Updated drawschedule",
				DRAWSCHEDULE_DELETED: "Deleted drawschedule",
				DRAWSCHEDULE_RETRIEVED: "Retrieved drawschedule details",
				DRAWSCHEDULES_RETRIEVED: "Retrieved drawschedule list",
			},
			PAGES: {
				DRAWSCHEDULE_CREATION: "DrawSchedule Creation",
				DRAWSCHEDULE_UPDATE: "DrawSchedule Update",
				DRAWSCHEDULE_DELETION: "DrawSchedule Deletion",
				DRAWSCHEDULE_DETAILS: "DrawSchedule Details",
				DRAWSCHEDULE_LIST: "DrawSchedule List",
			},
		},
		TERRITORY: {
			ACTIONS: {
				CREATE_TERRITORY: "CREATE_TERRITORY",
				GET_ALL_TERRITORY: "GET_ALL_TERRITORY",
				GET_TERRITORY: "GET_TERRITORY",
				UPDATE_TERRITORY: "UPDATE_TERRITORY",
				DELETE_TERRITORY: "DELETE_TERRITORY",
			},
			DESCRIPTIONS: {
				TERRITORY_CREATED: "Created new territory",
				TERRITORY_UPDATED: "Updated territory",
				TERRITORY_DELETED: "Deleted territory",
				TERRITORY_RETRIEVED: "Retrieved territory details",
				TERRITORYS_RETRIEVED: "Retrieved territory list",
			},
			PAGES: {
				TERRITORY_CREATION: "Territory Creation",
				TERRITORY_UPDATE: "Territory Update",
				TERRITORY_DELETION: "Territory Deletion",
				TERRITORY_DETAILS: "Territory Details",
				TERRITORY_LIST: "Territory List",
			},
		},
		AGENT: {
			ACTIONS: {
				CREATE_AGENT: "CREATE_AGENT",
				GET_ALL_AGENT: "GET_ALL_AGENT",
				GET_AGENT: "GET_AGENT",
				UPDATE_AGENT: "UPDATE_AGENT",
				DELETE_AGENT: "DELETE_AGENT",
			},
			DESCRIPTIONS: {
				AGENT_CREATED: "Created new agent",
				AGENT_UPDATED: "Updated agent",
				AGENT_DELETED: "Deleted agent",
				AGENT_RETRIEVED: "Retrieved agent details",
				AGENTS_RETRIEVED: "Retrieved agent list",
			},
			PAGES: {
				AGENT_CREATION: "Agent Creation",
				AGENT_UPDATE: "Agent Update",
				AGENT_DELETION: "Agent Deletion",
				AGENT_DETAILS: "Agent Details",
				AGENT_LIST: "Agent List",
			},
		},
		SESSION: {
			ACTIONS: {
				CREATE_SESSION: "CREATE_SESSION",
				GET_ALL_SESSION: "GET_ALL_SESSION",
				GET_SESSION: "GET_SESSION",
				UPDATE_SESSION: "UPDATE_SESSION",
				DELETE_SESSION: "DELETE_SESSION",
			},
			DESCRIPTIONS: {
				SESSION_CREATED: "Created new session",
				SESSION_UPDATED: "Updated session",
				SESSION_DELETED: "Deleted session",
				SESSION_RETRIEVED: "Retrieved session details",
				SESSIONS_RETRIEVED: "Retrieved session list",
			},
			PAGES: {
				SESSION_CREATION: "Session Creation",
				SESSION_UPDATE: "Session Update",
				SESSION_DELETION: "Session Deletion",
				SESSION_DETAILS: "Session Details",
				SESSION_LIST: "Session List",
			},
		},
		KYC: {
			ACTIONS: {
				CREATE_KYC: "CREATE_KYC",
				GET_ALL_KYC: "GET_ALL_KYC",
				GET_KYC: "GET_KYC",
				UPDATE_KYC: "UPDATE_KYC",
				DELETE_KYC: "DELETE_KYC",
			},
			DESCRIPTIONS: {
				KYC_CREATED: "Created new kyc",
				KYC_UPDATED: "Updated kyc",
				KYC_DELETED: "Deleted kyc",
				KYC_RETRIEVED: "Retrieved kyc details",
				KYCS_RETRIEVED: "Retrieved kyc list",
			},
			PAGES: {
				KYC_CREATION: "Kyc Creation",
				KYC_UPDATE: "Kyc Update",
				KYC_DELETION: "Kyc Deletion",
				KYC_DETAILS: "Kyc Details",
				KYC_LIST: "Kyc List",
			},
		},
		WALLET: {
			ACTIONS: {
				CREATE_WALLET: "CREATE_WALLET",
				GET_ALL_WALLET: "GET_ALL_WALLET",
				GET_WALLET: "GET_WALLET",
				UPDATE_WALLET: "UPDATE_WALLET",
				DELETE_WALLET: "DELETE_WALLET",
			},
			DESCRIPTIONS: {
				WALLET_CREATED: "Created new wallet",
				WALLET_UPDATED: "Updated wallet",
				WALLET_DELETED: "Deleted wallet",
				WALLET_RETRIEVED: "Retrieved wallet details",
				WALLETS_RETRIEVED: "Retrieved wallet list",
			},
			PAGES: {
				WALLET_CREATION: "Wallet Creation",
				WALLET_UPDATE: "Wallet Update",
				WALLET_DELETION: "Wallet Deletion",
				WALLET_DETAILS: "Wallet Details",
				WALLET_LIST: "Wallet List",
			},
		},
		TEMPLATE: {
			ACTIONS: {
				CREATE_TEMPLATE: "CREATE_TEMPLATE",
				GET_ALL_TEMPLATE: "GET_ALL_TEMPLATE",
				GET_TEMPLATE: "GET_TEMPLATE",
				UPDATE_TEMPLATE: "UPDATE_TEMPLATE",
				DELETE_TEMPLATE: "DELETE_TEMPLATE",
				USER_LOGIN: "USER_LOGIN",
				USER_LOGOUT: "USER_LOGOUT",
				USER_REGISTRATION: "USER_REGISTRATION",
				PASSWORD_UPDATE: "PASSWORD_UPDATE",
			},
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				TEMPLATE_RETRIEVED: "Retrieved template details",
				TEMPLATES_RETRIEVED: "Retrieved template list",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
				USER_REGISTERED: "User registered",
				PASSWORD_CHANGED: "Password changed",
			},
			PAGES: {
				TEMPLATE_CREATION: "Template Creation",
				TEMPLATE_UPDATE: "Template Update",
				TEMPLATE_DELETION: "Template Deletion",
				TEMPLATE_DETAILS: "Template Details",
				TEMPLATE_LIST: "Template List",
				USER_LOGIN: "User Login",
				USER_REGISTRATION: "User Registration",
				PASSWORD_CHANGE: "Password Change",
			},
		},
	},

	AUDIT_LOG: {
		ACTIONS: {
			CREATE: "CREATE",
			READ: "READ",
			UPDATE: "UPDATE",
			DELETE: "DELETE",
			LOGIN: "LOGIN",
			LOGOUT: "LOGOUT",
			REGISTER: "REGISTER",
		},
		RESOURCES: {
			TEMPLATE: "templates",
			USERS: "users",
			ORGANIZATIONS: "organizations",
			AUTH: "auth",
			SPORT: "sport",
			EVENT: "event",
			MARKET: "market",
			BET: "bet",
			WALLET: "wallet",
			PROMOTION: "promotion",
			KYC: "kyc",
			SESSION: "session",
			AGENT: "agent",
			TERRITORY: "territory",
			DRAWSCHEDULE: "drawschedule",
			JUETENGDRAW: "juetengdraw",
			JUETENGBET: "juetengbet",
			JUETENGCONFIG: "juetengconfig",
			JUETENGPAYOUT: "juetengpayout",
			COMMISSION: "commission",
			NOTIFICATION: "notification",
			OTP: "otp",
		},
		SEVERITY: {
			LOW: "LOW" as const,
			MEDIUM: "MEDIUM" as const,
			HIGH: "HIGH" as const,
			CRITICAL: "CRITICAL" as const,
		},
		ENTITY_TYPES: {
			TEMPLATE: "template",
			USER: "user",
			ORGANIZATION: "organization",
			SPORT: "sport",
			EVENT: "event",
			MARKET: "market",
			BET: "bet",
			WALLET: "wallet",
			PROMOTION: "promotion",
			KYC: "kyc",
			SESSION: "session",
			AGENT: "agent",
			TERRITORY: "territory",
			DRAWSCHEDULE: "drawschedule",
			JUETENGDRAW: "juetengdraw",
			JUETENGBET: "juetengbet",
			JUETENGCONFIG: "juetengconfig",
			JUETENGPAYOUT: "juetengpayout",
			COMMISSION: "commission",
			NOTIFICATION: "notification",
			OTP: "otp",
		},
		SPORT: {
			DESCRIPTIONS: {
				SPORT_CREATED: "Created new sport",
				SPORT_UPDATED: "Updated sport",
				SPORT_DELETED: "Deleted sport",
			},
		},
		EVENT: {
			DESCRIPTIONS: {
				EVENT_CREATED: "Created new event",
				EVENT_UPDATED: "Updated event",
				EVENT_DELETED: "Deleted event",
			},
		},
		MARKET: {
			DESCRIPTIONS: {
				MARKET_CREATED: "Created new market",
				MARKET_UPDATED: "Updated market",
				MARKET_DELETED: "Deleted market",
			},
		},
		BET: {
			DESCRIPTIONS: {
				BET_CREATED: "Created new bet",
				BET_UPDATED: "Updated bet",
				BET_DELETED: "Deleted bet",
			},
		},
		WALLET: {
			DESCRIPTIONS: {
				WALLET_CREATED: "Created new wallet",
				WALLET_UPDATED: "Updated wallet",
				WALLET_DELETED: "Deleted wallet",
			},
		},
		PROMOTION: {
			DESCRIPTIONS: {
				PROMOTION_CREATED: "Created new promotion",
				PROMOTION_UPDATED: "Updated promotion",
				PROMOTION_DELETED: "Deleted promotion",
			},
		},
		KYC: {
			DESCRIPTIONS: {
				KYC_CREATED: "Created new kyc",
				KYC_UPDATED: "Updated kyc",
				KYC_DELETED: "Deleted kyc",
			},
		},
		SESSION: {
			DESCRIPTIONS: {
				SESSION_CREATED: "Created new session",
				SESSION_UPDATED: "Updated session",
				SESSION_DELETED: "Deleted session",
			},
		},
		AGENT: {
			DESCRIPTIONS: {
				AGENT_CREATED: "Created new agent",
				AGENT_UPDATED: "Updated agent",
				AGENT_DELETED: "Deleted agent",
			},
		},
		TERRITORY: {
			DESCRIPTIONS: {
				TERRITORY_CREATED: "Created new territory",
				TERRITORY_UPDATED: "Updated territory",
				TERRITORY_DELETED: "Deleted territory",
			},
		},
		DRAWSCHEDULE: {
			DESCRIPTIONS: {
				DRAWSCHEDULE_CREATED: "Created new drawschedule",
				DRAWSCHEDULE_UPDATED: "Updated drawschedule",
				DRAWSCHEDULE_DELETED: "Deleted drawschedule",
			},
		},
		JUETENGDRAW: {
			DESCRIPTIONS: {
				JUETENGDRAW_CREATED: "Created new juetengdraw",
				JUETENGDRAW_UPDATED: "Updated juetengdraw",
				JUETENGDRAW_DELETED: "Deleted juetengdraw",
			},
		},
		JUETENGBET: {
			DESCRIPTIONS: {
				JUETENGBET_CREATED: "Created new juetengbet",
				JUETENGBET_UPDATED: "Updated juetengbet",
				JUETENGBET_DELETED: "Deleted juetengbet",
			},
		},
		JUETENGCONFIG: {
			DESCRIPTIONS: {
				JUETENGCONFIG_CREATED: "Created new juetengconfig",
				JUETENGCONFIG_UPDATED: "Updated juetengconfig",
				JUETENGCONFIG_DELETED: "Deleted juetengconfig",
			},
		},
		JUETENGPAYOUT: {
			DESCRIPTIONS: {
				JUETENGPAYOUT_CREATED: "Created new juetengpayout",
				JUETENGPAYOUT_UPDATED: "Updated juetengpayout",
				JUETENGPAYOUT_DELETED: "Deleted juetengpayout",
			},
		},
		COMMISSION: {
			DESCRIPTIONS: {
				COMMISSION_CREATED: "Created new commission",
				COMMISSION_UPDATED: "Updated commission",
				COMMISSION_DELETED: "Deleted commission",
			},
		},
		NOTIFICATION: {
			DESCRIPTIONS: {
				NOTIFICATION_CREATED: "Created new notification",
				NOTIFICATION_UPDATED: "Updated notification",
				NOTIFICATION_DELETED: "Deleted notification",
			},
		},

		TEMPLATE: {
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				USER_CREATED: "Created new user",
				USER_UPDATED: "Updated user",
				USER_DELETED: "Deleted user",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
			},
		},
	},
};
